packages:
  # all packages in direct subdirs of packages/
  - "packages/*"
  # all packages in subdirs of components/
  - "examples/*"
  # all packages in subdirs of tooling/
  - "tooling/*"
  # all packages in subdirs of docs/
  - "docs/*"
  # exclude packages that are inside test directories
  - "!**/test/**"
